export const INVITES = [
  "Azu Rivera",
  "Lupita Soto",
  "Ale Rosales",
  "Lupita Pineda",
  "Viri Perez",
  "Pame Adan",
  "Dany Carranza",
  "Raque García",
  "Aurelio Valdés",
  "Raul Morales",
  "Vicky García",
  "Jorge Mati",
  "Cesar Gdm",
  "María Arevalo",
  "Rodri Esquivel",
  "Victor Esquivel",
  "Jaime León",
  "Cocoy",
  "Pao Rodea",
  "Erick Ruiz",
  "Fany Mejía",
  "Ros Consuelo",
  "Majo Rosales",
  "Emiliano",
  "José Rosales",
  "Maritza Colin",
  "Pablo Rosales",
  "Tete Santín",
  "Prim",
  "Omar Cisneros",
  "Peco",
  "Luis Arias",
  "Mayalen Leon",
  "Pam Lorenzin",
  "Fer Sánchez",
  "Fer Yañez",
  "Leo Ritter",
  "Madrina",
  "Padrino",
  "Tía Fabiola",
  "Elias Rosales",
  "Caro Muñoz",
  "Abue Gaby",
  "Lulu Brito",
  "Eve Rosales",
  "Alfredito",
  "Novia Alfredito",
];
